### ISSUE TITLE
`qiskit-ibm-catalog` version isn't correctly setup

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit-ibm-catalog#10]
### Steps to reproduce the problem

While we have [VERSION.txt](https://github.com/Qiskit/qiskit-ibm-catalog/blob/main/qiskit_ibm_catalog/VERSION.txt), this version isn't propagated to PyPi

### What is the current behavior?

Today, when running `!pip freeze | grep qiskit`, it only shows `qiskit-ibm-catalog==0.0.0`

### What is the expected behavior?

It should correctly reference our version

**Comment by psschwei** [comment]
Believe this was fixed in #15

**Comment by HuangJunye** [comment]
Can't find 0.2.0 from pypi. I think #15 didn't fix the issue.
```
pip install qiskit-ibm-catalog==0.2.0
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.11; 0.2.0 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement qiskit-ibm-catalog==0.2.0 (from versions: 0.0.0)
ERROR: No matching distribution found for qiskit-ibm-catalog==0.2.0
```

**Comment by HuangJunye** [comment]
Updating to python 3.11 solved the issue. Please ignore my previous comments :D
